/sensors/channel:
    get:
      tags:
        - server settings
      summary: Fetch all channel settings whether disabled or enabled.
      security:
        - cognitoAuth: []
      parameters:
        - in: query
          name: lid
          schema:
            type: integer
          required: true
          description: Numeric database ID of the logger
        - in: query
          name: ch
          schema:
            type: string
          required: true
          description: The letter pertaining to the channel (a,b,c or d) 
      responses:
        "200":
          description: Array of JSON objects each containing the sensor state.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "x1018"
                        description: Sensor ID
                      state:
                        type: integer
                        example: 1 
                        description: 1 = enabled, 0 = disabled
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
    put:
      tags:
          - server settings
      summary: Enables or disables channel sensor.
      security:
        - cognitoAuth: []
      consumes:
        - application/json
      requestBody:
        description: An object containing data about which logger and sensor to update
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ch:
                  type: string
                  example: "a"
                  description: Letter denoting the channel a,b,c or d
                lid:
                  type: integer
                  example: 524
                  description: database primary key of logger
                sensor_id:
                  type: string
                  example: x1001
                value:
                  type: integer
                  example: 0
                  description: The new value 1 = enable, 0 = disable
      responses:
        "200":
          description: A JSON objects containing the database update result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  fieldCount:
                    type: integer
                    example: 0
                    description: Can be ignored
                  affectedRows:
                    type: integer
                    example: 1 
                    description: The number of rows affected in the database. Should = 1.
                  insertId:
                    type: integer
                    example: 0 
                    description: Can be ignored. Should - 0.  
                  info:
                    type: string
                    example: "Rows matched: 1 Changed: 1 Warnings: 0"
                    description: Some information about the result of the request.  
                  serverStatus:
                    type: integer
                    example: 34 
                    description: Flags indicating the server status. Can be ignored   
                  warningStatus:
                    type: integer
                    example: 0 
                  changedRows:
                    type: integer
                    example: 1 
                    description: Indicates the number of rows changed. Should = 1.               