openapi: 3.0.0
info:
  version: 1.0.0
  title: Xpert 
  description: Xpert API Documentation
tags:
  - name: customer
    description: resources belonging to a customer
  - name: dynamodb
    description: Data from AWS DynamoDb
  - name: group
    description: resources relating to group
  - name: licenses
    description: all things license related
  - name: logger
    description: all things logger related
  - name: loggers
    description: all things related to a collective group of loggers
  - name: user
    description: resources belonging to a user
  - name: users
    description: users of the xpert system - SECURED WITH AUTHORIZER
  
paths:
  /customer/loggers/:
    $ref: "paths/customer-loggers.yaml"
  /logger/:
    $ref: "paths/logger.yaml"
  /users/:
    $ref: "paths/users.yaml"
  /user/loggers/:
    $ref: "paths/user-loggers.yaml"
  /user/groups/:
    $ref: "paths/user-groups.yaml"                 
  /group/loggers/:
    $ref: "paths/group-loggers.yaml"
  /loggers/coords/:
    $ref: "paths/loggers-coords.yaml"  
  /licenses/customer/:
    $ref: "paths/licenses-customer.yaml"
  /licenses/logger/:
    $ref: "paths/licenses-logger.yaml"  
  /licenses/logger/latest/:
    $ref: "paths/licenses-logger-latest.yaml" 
  /licenses/renew/:
    $ref: "paths/licenses-renew.yaml"    
  /dynamodb/diagnostic/:
    $ref: "path/dynamodb-diagnostic.yaml"